import React, { useState } from 'react';
import { apiClient } from '@/lib/api/client';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';

export default function AuthTester() {
  const [logs, setLogs] = useState<{ time: string; msg: string; status: 'info' | 'success' | 'error' }[]>([]);

  const addLog = (msg: string, status: 'info' | 'success' | 'error' = 'info') => {
    setLogs((prev) => [...prev, { time: new Date().toLocaleTimeString(), msg, status }]);
  };

  const runTest = async () => {
    setLogs([]);
    addLog('Starting API Verification Flow...', 'info');

    try {
      // 1. Fetch CSRF Cookie
      addLog('1. Fetching Sanctum CSRF cookie...');
      await apiClient.get('/sanctum/csrf-cookie');
      addLog('CSRF cookie set successfully.', 'success');

      // 2. Login
      addLog('2. Attempting login...');
      // Note: We assume an admin user exists. Let's use the one generated by factory in DB seeder, 
      // or we can test with a known credential. 
      // If we don't know the credential, this step might fail with 401/422, which still proves API is connected.
      try {
        await apiClient.post('/api/login', {
          email: 'admin@portfolio.test', // Change if different
          password: 'password', // Default Laravel factory password
        });
        addLog('Login successful!', 'success');
      } catch (err: any) {
        if (err.status === 401 || err.status === 422) {
          addLog(`Login failed (invalid credentials), but API is reachable. Error: ${err.message}`, 'error');
          return; // Stop flow
        }
        throw err;
      }

      // 3. GET User
      addLog('3. Fetching authenticated user...');
      const userRes = await apiClient.get('/api/user');
      addLog(`User fetched: ${userRes.data?.data?.name || userRes.data?.name || 'Unknown'}`, 'success');

      // 4. Logout
      addLog('4. Logging out...');
      await apiClient.post('/api/logout');
      addLog('Logged out successfully.', 'success');

      // 5. Protected Request (Should Reject)
      addLog('5. Fetching user again (should be rejected)...');
      try {
        await apiClient.get('/api/user');
        addLog('Error: Request was NOT rejected!', 'error');
      } catch (err: any) {
        addLog(`Request correctly rejected: ${err.message}`, 'success');
        addLog('✅ All verification steps passed successfully!', 'success');
      }
    } catch (error: any) {
      addLog(`Flow interrupted by error: ${error.message || 'Unknown error'}`, 'error');
    }
  };

  return (
    <div className="min-h-screen bg-background p-8 flex flex-col items-center">
      <Card className="w-full max-w-2xl">
        <CardHeader>
          <CardTitle>Sanctum API Verification</CardTitle>
          <CardDescription>Tests the CSRF and Login flow against the Laravel Backend</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <Button onClick={runTest}>Run Flow</Button>
          
          <div className="bg-secondary/30 p-4 rounded-md space-y-2 h-96 overflow-y-auto font-mono text-sm border border-border">
            {logs.length === 0 && <span className="text-muted-foreground">Click "Run Flow" to begin...</span>}
            {logs.map((log, i) => (
              <div key={i} className="flex gap-2">
                <span className="text-muted-foreground shrink-0">[{log.time}]</span>
                <span className={
                  log.status === 'success' ? 'text-green-500' :
                  log.status === 'error' ? 'text-red-500' :
                  'text-foreground'
                }>
                  {log.msg}
                </span>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
